{% set name = "natasha" %}
{% set version = "1.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/natasha-{{ version }}.tar.gz
  sha256: 46082e6b382ad3a6bc07d8de4677c70f955347e5eb77ef0e0ac4147da18b12ad

build:
  skip: true  # [win]
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - ipymarkup >=0.8.0
    - navec >=0.10.0
    - pymorphy2
    - python
    - razdel >=0.5.0
    - slovnet >=0.5.0
    - yargy >=0.15.0

test:
  imports:
    - natasha
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/natasha/natasha
  summary: Named-entity recognition for russian language.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - harri-pltr
